### ISSUE TITLE
Limit the use of .theme-dark

### ISSUE THREAD

**Issue by L-m-b** [HoLLy-HaCKeR/DiscordCSS#3]
You should use #app-mount rather than .theme-dark when applying styles to discord, as otherwise you have to use !important on a load of elements, and using #app-mount also makes it compatible to work with both dark AND light. Also any client mods are insecure, some more than others, but all the same.

**Comment by HoLLy-HaCKeR** [comment]
> Also any client mods are insecure, some more than others, but all the same.
While client mods such as BetterDiscord have auto-update functionality and could so be seen as insecure, I use (and recommend) BeautifulDiscord, which is opensource and functions completely offline. It doesn't get much more secure than that.

`#app-mount` and `.theme-dark` are applied to different elements. In most cases, you can't just swap them around and have everything work. Also, since I'm making nearly everything transparent there is no point in having the white theme selected, so you could just switch to that for the time being.

I'll see if I can rely less on .theme-dark and more on #app-mount or equivalent selectors, but I believe it will rather require more `!important` attributes, since Discord's CSS rules use it and style tags overrule external stylesheets.
